import 'dart:convert';

import 'package:flutter/services.dart';

List arabic = [];
List malayalam = [];
List quran = [];
Future readJson() async {
  String response =
      await rootBundle.loadString("assets/quran/hafs_smart_v8.json");
  Map<String, dynamic> data = json.decode(response);
  arabic = data["quran"];
  malayalam = data["malayalam"];

  return quran = [arabic, malayalam];
}

List<Map> listOfSurahInfo = [
  {
    "surah": "1",
    "name": "الفاتحة",
    "ayah": "7",
    "type": "مكية",
  },
  {
    "surah": "2",
    "name": "البقرة",
    "ayah": "286",
    "type": "مدنية",
  },
  {
    "surah": "3",
    "name": "آل عمران",
    "ayah": "200",
    "type": "مدنية",
  },
  {
    "surah": "4",
    "name": "النساء",
    "ayah": "176",
    "type": "مدنية",
  },
  {
    "surah": "5",
    "name": "المائدة",
    "ayah": "120",
    "type": "مدنية",
  },
  {
    "surah": "6",
    "name": "الأنعام",
    "ayah": "165",
    "type": "مكية",
  },
  {
    "surah": "7",
    "name": "الأعراف",
    "ayah": "206",
    "type": "مكية",
  },
  {
    "surah": "8",
    "name": "الأنفال",
    "ayah": "75",
    "type": "مدنية",
  },
  {
    "surah": "9",
    "name": "التوبة",
    "ayah": "129",
    "type": "مدنية",
  },
  {
    "surah": "10",
    "name": "يونس",
    "ayah": "109",
    "type": "مكية",
  },
  {
    "surah": "11",
    "name": "هود",
    "ayah": "123",
    "type": "مكية",
  },
  {
    "surah": "12",
    "name": "يوسف",
    "ayah": "111",
    "type": "مكية",
  },
  {
    "surah": "13",
    "name": "الرعد",
    "ayah": "43",
    "type": "مدنية",
  },
  {
    "surah": "14",
    "name": "ابراهيم",
    "ayah": "52",
    "type": "مكية",
  },
  {
    "surah": "15",
    "name": "الحجر",
    "ayah": "99",
    "type": "مكية",
  },
  {
    "surah": "16",
    "name": "النحل",
    "ayah": "128",
    "type": "مكية",
  },
  {
    "surah": "17",
    "name": "الإسراء",
    "ayah": "111",
    "type": "مكية",
  },
  {
    "surah": "18",
    "name": "الكهف",
    "ayah": "110",
    "type": "مكية",
  },
  {
    "surah": "19",
    "name": "مريم",
    "ayah": "98",
    "type": "مكية",
  },
  {
    "surah": "20",
    "name": "طه",
    "ayah": "135",
    "type": "مكية",
  },
  {
    "surah": "21",
    "name": "الأنبياء",
    "ayah": "112",
    "type": "مكية",
  },
  {
    "surah": "22",
    "name": "الحج",
    "ayah": "78",
    "type": "مدنية",
  },
  {
    "surah": "23",
    "name": "المؤمنون",
    "ayah": "118",
    "type": "مكية",
  },
  {
    "surah": "24",
    "name": "النور",
    "ayah": "64",
    "type": "مدنية",
  },
  {
    "surah": "25",
    "name": "الفرقان",
    "ayah": "77",
    "type": "مكية",
  },
  {
    "surah": "26",
    "name": "الشعراء",
    "ayah": "227",
    "type": "مكية",
  },
  {
    "surah": "27",
    "name": "النمل",
    "ayah": "93",
    "type": "مكية",
  },
  {
    "surah": "28",
    "name": "القصص",
    "ayah": "88",
    "type": "مكية",
  },
  {
    "surah": "29",
    "name": "العنكبوت",
    "ayah": "69",
    "type": "مكية",
  },
  {
    "surah": "30",
    "name": "الروم",
    "ayah": "60",
    "type": "مكية",
  },
  {
    "surah": "31",
    "name": "لقمان",
    "ayah": "34",
    "type": "مكية",
  },
  {
    "surah": "32",
    "name": "السجدة",
    "ayah": "30",
    "type": "مكية",
  },
  {
    "surah": "33",
    "name": "الأحزاب",
    "ayah": "73",
    "type": "مدنية",
  },
  {
    "surah": "34",
    "name": "سبإ",
    "ayah": "54",
    "type": "مكية",
  },
  {
    "surah": "35",
    "name": "فاطر",
    "ayah": "45",
    "type": "مكية",
  },
  {
    "surah": "36",
    "name": "يس",
    "ayah": "83",
    "type": "مكية",
  },
  {
    "surah": "37",
    "name": "الصافات",
    "ayah": "182",
    "type": "مكية",
  },
  {
    "surah": "38",
    "name": "ص",
    "ayah": "88",
    "type": "مكية",
  },
  {
    "surah": "39",
    "name": "الزمر",
    "ayah": "75",
    "type": "مكية",
  },
  {
    "surah": "40",
    "name": "غافر",
    "ayah": "85",
    "type": "مكية",
  },
  {
    "surah": "41",
    "name": "فصلت",
    "ayah": "54",
    "type": "مكية",
  },
  {
    "surah": "42",
    "name": "الشورى",
    "ayah": "53",
    "type": "مكية",
  },
  {
    "surah": "43",
    "name": "الزخرف",
    "ayah": "89",
    "type": "مكية",
  },
  {
    "surah": "44",
    "name": "الدخان",
    "ayah": "59",
    "type": "مكية",
  },
  {
    "surah": "45",
    "name": "الجاثية",
    "ayah": "37",
    "type": "مكية",
  },
  {
    "surah": "46",
    "name": "الأحقاف",
    "ayah": "35",
    "type": "مكية",
  },
  {
    "surah": "47",
    "name": "محمد",
    "ayah": "38",
    "type": "مدنية",
  },
  {
    "surah": "48",
    "name": "الفتح",
    "ayah": "29",
    "type": "مدنية",
  },
  {
    "surah": "49",
    "name": "الحجرات",
    "ayah": "18",
    "type": "مدنية",
  },
  {
    "surah": "50",
    "name": "ق",
    "ayah": "45",
    "type": "مكية",
  },
  {
    "surah": "51",
    "name": "الذاريات",
    "ayah": "60",
    "type": "مكية",
  },
  {
    "surah": "52",
    "name": "الطور",
    "ayah": "49",
    "type": "مكية",
  },
  {
    "surah": "53",
    "name": "النجم",
    "ayah": "62",
    "type": "مكية",
  },
  {
    "surah": "54",
    "name": "القمر",
    "ayah": "55",
    "type": "مكية",
  },
  {
    "surah": "55",
    "name": "الرحمن",
    "ayah": "78",
    "type": "مدنية",
  },
  {
    "surah": "56",
    "name": "الواقعة",
    "ayah": "96",
    "type": "مكية",
  },
  {
    "surah": "57",
    "name": "الحديد",
    "ayah": "29",
    "type": "مدنية",
  },
  {
    "surah": "58",
    "name": "المجادلة",
    "ayah": "22",
    "type": "مدنية",
  },
  {
    "surah": "59",
    "name": "الحشر",
    "ayah": "24",
    "type": "مدنية",
  },
  {
    "surah": "60",
    "name": "الممتحنة",
    "ayah": "13",
    "type": "مكية",
  },
  {
    "surah": "61",
    "name": "الصف",
    "ayah": "14",
    "type": "مدنية",
  },
  {
    "surah": "62",
    "name": "الجمعة",
    "ayah": "11",
    "type": "مدنية",
  },
  {
    "surah": "63",
    "name": "المنافقون",
    "ayah": "11",
    "type": "مدنية",
  },
  {
    "surah": "64",
    "name": "التغابن",
    "ayah": "18",
    "type": "مدنية",
  },
  {
    "surah": "65",
    "name": "الطلاق",
    "ayah": "12",
    "type": "مدنية",
  },
  {
    "surah": "66",
    "name": "التحريم",
    "ayah": "12",
    "type": "مدنية",
  },
  {
    "surah": "67",
    "name": "الملك",
    "ayah": "30",
    "type": "مكية",
  },
  {
    "surah": "68",
    "name": "القلم",
    "ayah": "52",
    "type": "مكية",
  },
  {
    "surah": "69",
    "name": "الحاقة",
    "ayah": "52",
    "type": "مكية",
  },
  {
    "surah": "70",
    "name": "المعارج",
    "ayah": "44",
    "type": "مكية",
  },
  {
    "surah": "71",
    "name": "نوح",
    "ayah": "28",
    "type": "مكية",
  },
  {
    "surah": "72",
    "name": "الجن",
    "ayah": "28",
    "type": "مكية",
  },
  {
    "surah": "73",
    "name": "المزمل",
    "ayah": "20",
    "type": "مكية",
  },
  {
    "surah": "74",
    "name": "المدثر",
    "ayah": "56",
    "type": "مكية",
  },
  {
    "surah": "75",
    "name": "القيامة",
    "ayah": "40",
    "type": "مكية",
  },
  {
    "surah": "76",
    "name": "الانسان",
    "ayah": "31",
    "type": "مدنية",
  },
  {
    "surah": "77",
    "name": "المرسلات",
    "ayah": "50",
    "type": "مكية",
  },
  {
    "surah": "78",
    "name": "النبإ",
    "ayah": "40",
    "type": "مكية",
  },
  {
    "surah": "79",
    "name": "النازعات",
    "ayah": "46",
    "type": "مكية",
  },
  {
    "surah": "80",
    "name": "عبس",
    "ayah": "42",
    "type": "مكية",
  },
  {
    "surah": "81",
    "name": "التكوير",
    "ayah": "29",
    "type": "مكية",
  },
  {
    "surah": "82",
    "name": "الإنفطار",
    "ayah": "19",
    "type": "مكية",
  },
  {
    "surah": "83",
    "name": "المطففين",
    "ayah": "36",
    "type": "مكية",
  },
  {
    "surah": "84",
    "name": "الإنشقاق",
    "ayah": "25",
    "type": "مكية",
  },
  {
    "surah": "85",
    "name": "البروج",
    "ayah": "22",
    "type": "مكية",
  },
  {
    "surah": "86",
    "name": "الطارق",
    "ayah": "17",
    "type": "مكية",
  },
  {
    "surah": "87",
    "name": "الأعلى",
    "ayah": "19",
    "type": "مكية",
  },
  {
    "surah": "88",
    "name": "الغاشية",
    "ayah": "26",
    "type": "مكية",
  },
  {
    "surah": "89",
    "name": "الفجر",
    "ayah": "30",
    "type": "مكية",
  },
  {
    "surah": "90",
    "name": "البلد",
    "ayah": "20",
    "type": "مكية",
  },
  {
    "surah": "91",
    "name": "الشمس",
    "ayah": "15",
    "type": "مكية",
  },
  {
    "surah": "92",
    "name": "الليل",
    "ayah": "21",
    "type": "مكية",
  },
  {
    "surah": "93",
    "name": "الضحى",
    "ayah": "11",
    "type": "مكية",
  },
  {
    "surah": "94",
    "name": "الشرح",
    "ayah": "8",
    "type": "مكية",
  },
  {
    "surah": "95",
    "name": "التين",
    "ayah": "8",
    "type": "مكية",
  },
  {
    "surah": "96",
    "name": "العلق",
    "ayah": "19",
    "type": "مكية",
  },
  {
    "surah": "97",
    "name": "القدر",
    "ayah": "5",
    "type": "مكية",
  },
  {
    "surah": "98",
    "name": "البينة",
    "ayah": "8",
    "type": "مدنية",
  },
  {
    "surah": "99",
    "name": "الزلزلة",
    "ayah": "8",
    "type": "مدنية",
  },
  {
    "surah": "100",
    "name": "العاديات",
    "ayah": "9",
    "type": "مدنية",
  },
  {
    "surah": "101",
    "name": "القارعة",
    "ayah": "11",
    "type": "مكية",
  },
  {
    "surah": "102",
    "name": "التكاثر",
    "ayah": "8",
    "type": "مكية",
  },
  {
    "surah": "103",
    "name": "العصر",
    "ayah": "3",
    "type": "مكية",
  },
  {
    "surah": "104",
    "name": "الهمزة",
    "ayah": "9",
    "type": "مكية",
  },
  {
    "surah": "105",
    "name": "الفيل",
    "ayah": "5",
    "type": "مكية",
  },
  {
    "surah": "106",
    "name": "قريش",
    "ayah": "4",
    "type": "مكية",
  },
  {
    "surah": "107",
    "name": "الماعون",
    "ayah": "7",
    "type": "مكية",
  },
  {
    "surah": "108",
    "name": "الكوثر",
    "ayah": "3",
    "type": "مكية",
  },
  {
    "surah": "109",
    "name": "الكافرون",
    "ayah": "6",
    "type": "مكية",
  },
  {
    "surah": "110",
    "name": "النصر",
    "ayah": "3",
    "type": "مدنية",
  },
  {
    "surah": "111",
    "name": "المسد",
    "ayah": "5",
    "type": "مكية",
  },
  {
    "surah": "112",
    "name": "الإخلاص",
    "ayah": "4",
    "type": "مكية",
  },
  {
    "surah": "113",
    "name": "الفلق",
    "ayah": "5",
    "type": "مكية",
  },
  {
    "surah": "114",
    "name": "الناس",
    "ayah": "6",
    "type": "مكية",
  }
];
